import React, { useEffect } from 'react';
import PropTypes from 'prop-types';
import { useTranslation } from '../../../contexts/i18n';
import loadScript from '../../../utils/load-script';
import styles from './world-map.module.scss';

const WorldMap = ({ data, onReady }) => {
  const { tab, values } = data;
  const { t } = useTranslation();

  const options = {
    map: 'world_merc',
    backgroundColor: 'transparent',
    zoomOnScroll: false,
    regionStyle: {
      initial: {
        fill: '#dce1f6',
        stroke: 'none',
        'stroke-width': 0,
        'stroke-opacity': 0
      },
      hover: {
        fill: '#174ea6'
      },
      selected: {},
      selectedHover: {}
    },
    onRegionTipShow: (e, tip, code) => {
      tip.html(
        `<ul><li>${t(`countries.${code}`)}</li><li>${
          values[code] || '0'
        }</li></ul>`
      );
    },
    series: {
      regions: [
        {
          values,
          scale: ['#dce1f6', '#8596e1'],
          normalizeFunction: 'polynomial'
        }
      ]
    }
  };

  useEffect(() => {
    loadScript('jquery-3.6.0.min.js', () => {
      loadScript('jquery-jvectormap-2.0.5.min.js', () => {
        loadScript('jquery-jvectormap-world-merc.js', () => {
          // eslint-disable-next-line no-undef
          $(`#${tab}-world-map`).vectorMap(options);
          if (onReady) onReady();
        });
      });
    });
  }, []);

  return <div id={`${tab}-world-map`} className={styles['world-map']} />;
};

WorldMap.propTypes = {
  data: PropTypes.shape({
    tab: PropTypes.string,
    values: PropTypes.shape({
      AD: PropTypes.number,
      AE: PropTypes.number,
      AF: PropTypes.number,
      AG: PropTypes.number,
      AI: PropTypes.number,
      AL: PropTypes.number,
      AM: PropTypes.number,
      AO: PropTypes.number,
      AQ: PropTypes.number,
      AR: PropTypes.number,
      AS: PropTypes.number,
      AT: PropTypes.number,
      AU: PropTypes.number,
      AW: PropTypes.number,
      AX: PropTypes.number,
      AZ: PropTypes.number,
      BA: PropTypes.number,
      BB: PropTypes.number,
      BD: PropTypes.number,
      BE: PropTypes.number,
      BF: PropTypes.number,
      BG: PropTypes.number,
      BH: PropTypes.number,
      BI: PropTypes.number,
      BJ: PropTypes.number,
      BL: PropTypes.number,
      BM: PropTypes.number,
      BN: PropTypes.number,
      BO: PropTypes.number,
      BQ: PropTypes.number,
      BR: PropTypes.number,
      BS: PropTypes.number,
      BT: PropTypes.number,
      BV: PropTypes.number,
      BW: PropTypes.number,
      BY: PropTypes.number,
      BZ: PropTypes.number,
      CA: PropTypes.number,
      CC: PropTypes.number,
      CD: PropTypes.number,
      CF: PropTypes.number,
      CG: PropTypes.number,
      CH: PropTypes.number,
      CI: PropTypes.number,
      CK: PropTypes.number,
      CL: PropTypes.number,
      CM: PropTypes.number,
      CN: PropTypes.number,
      CO: PropTypes.number,
      CR: PropTypes.number,
      CU: PropTypes.number,
      CV: PropTypes.number,
      CW: PropTypes.number,
      CX: PropTypes.number,
      CY: PropTypes.number,
      CZ: PropTypes.number,
      DE: PropTypes.number,
      DJ: PropTypes.number,
      DK: PropTypes.number,
      DM: PropTypes.number,
      DO: PropTypes.number,
      DZ: PropTypes.number,
      EC: PropTypes.number,
      EE: PropTypes.number,
      EG: PropTypes.number,
      EH: PropTypes.number,
      ER: PropTypes.number,
      ES: PropTypes.number,
      ET: PropTypes.number,
      FI: PropTypes.number,
      FJ: PropTypes.number,
      FK: PropTypes.number,
      FM: PropTypes.number,
      FO: PropTypes.number,
      FR: PropTypes.number,
      GA: PropTypes.number,
      GB: PropTypes.number,
      GD: PropTypes.number,
      GE: PropTypes.number,
      GF: PropTypes.number,
      GG: PropTypes.number,
      GH: PropTypes.number,
      GI: PropTypes.number,
      GL: PropTypes.number,
      GM: PropTypes.number,
      GN: PropTypes.number,
      GP: PropTypes.number,
      GQ: PropTypes.number,
      GR: PropTypes.number,
      GS: PropTypes.number,
      GT: PropTypes.number,
      GU: PropTypes.number,
      GW: PropTypes.number,
      GY: PropTypes.number,
      HK: PropTypes.number,
      HM: PropTypes.number,
      HN: PropTypes.number,
      HR: PropTypes.number,
      HT: PropTypes.number,
      HU: PropTypes.number,
      ID: PropTypes.number,
      IE: PropTypes.number,
      IL: PropTypes.number,
      IM: PropTypes.number,
      IN: PropTypes.number,
      IO: PropTypes.number,
      IQ: PropTypes.number,
      IR: PropTypes.number,
      IS: PropTypes.number,
      IT: PropTypes.number,
      JE: PropTypes.number,
      JM: PropTypes.number,
      JO: PropTypes.number,
      JP: PropTypes.number,
      KE: PropTypes.number,
      KG: PropTypes.number,
      KH: PropTypes.number,
      KI: PropTypes.number,
      KM: PropTypes.number,
      KN: PropTypes.number,
      KP: PropTypes.number,
      KR: PropTypes.number,
      KW: PropTypes.number,
      KY: PropTypes.number,
      KZ: PropTypes.number,
      LA: PropTypes.number,
      LB: PropTypes.number,
      LC: PropTypes.number,
      LI: PropTypes.number,
      LK: PropTypes.number,
      LR: PropTypes.number,
      LS: PropTypes.number,
      LT: PropTypes.number,
      LU: PropTypes.number,
      LV: PropTypes.number,
      LY: PropTypes.number,
      MA: PropTypes.number,
      MC: PropTypes.number,
      MD: PropTypes.number,
      ME: PropTypes.number,
      MF: PropTypes.number,
      MG: PropTypes.number,
      MH: PropTypes.number,
      MK: PropTypes.number,
      ML: PropTypes.number,
      MM: PropTypes.number,
      MN: PropTypes.number,
      MO: PropTypes.number,
      MP: PropTypes.number,
      MQ: PropTypes.number,
      MR: PropTypes.number,
      MS: PropTypes.number,
      MT: PropTypes.number,
      MU: PropTypes.number,
      MV: PropTypes.number,
      MW: PropTypes.number,
      MX: PropTypes.number,
      MY: PropTypes.number,
      MZ: PropTypes.number,
      NA: PropTypes.number,
      NC: PropTypes.number,
      NE: PropTypes.number,
      NF: PropTypes.number,
      NG: PropTypes.number,
      NI: PropTypes.number,
      NL: PropTypes.number,
      NO: PropTypes.number,
      NP: PropTypes.number,
      NR: PropTypes.number,
      NU: PropTypes.number,
      NZ: PropTypes.number,
      OM: PropTypes.number,
      PA: PropTypes.number,
      PE: PropTypes.number,
      PF: PropTypes.number,
      PG: PropTypes.number,
      PH: PropTypes.number,
      PK: PropTypes.number,
      PL: PropTypes.number,
      PM: PropTypes.number,
      PN: PropTypes.number,
      PR: PropTypes.number,
      PS: PropTypes.number,
      PT: PropTypes.number,
      PW: PropTypes.number,
      PY: PropTypes.number,
      QA: PropTypes.number,
      RE: PropTypes.number,
      RO: PropTypes.number,
      RS: PropTypes.number,
      RU: PropTypes.number,
      RW: PropTypes.number,
      SA: PropTypes.number,
      SB: PropTypes.number,
      SC: PropTypes.number,
      SD: PropTypes.number,
      SE: PropTypes.number,
      SG: PropTypes.number,
      SH: PropTypes.number,
      SI: PropTypes.number,
      SJ: PropTypes.number,
      SK: PropTypes.number,
      SL: PropTypes.number,
      SM: PropTypes.number,
      SN: PropTypes.number,
      SO: PropTypes.number,
      SR: PropTypes.number,
      SS: PropTypes.number,
      ST: PropTypes.number,
      SV: PropTypes.number,
      SX: PropTypes.number,
      SY: PropTypes.number,
      SZ: PropTypes.number,
      TC: PropTypes.number,
      TD: PropTypes.number,
      TF: PropTypes.number,
      TG: PropTypes.number,
      TH: PropTypes.number,
      TJ: PropTypes.number,
      TK: PropTypes.number,
      TL: PropTypes.number,
      TM: PropTypes.number,
      TN: PropTypes.number,
      TO: PropTypes.number,
      TR: PropTypes.number,
      TT: PropTypes.number,
      TV: PropTypes.number,
      TW: PropTypes.number,
      TZ: PropTypes.number,
      UA: PropTypes.number,
      UG: PropTypes.number,
      UM: PropTypes.number,
      US: PropTypes.number,
      UY: PropTypes.number,
      UZ: PropTypes.number,
      VA: PropTypes.number,
      VC: PropTypes.number,
      VE: PropTypes.number,
      VG: PropTypes.number,
      VI: PropTypes.number,
      VN: PropTypes.number,
      VU: PropTypes.number,
      WF: PropTypes.number,
      WS: PropTypes.number,
      YE: PropTypes.number,
      YT: PropTypes.number,
      ZA: PropTypes.number,
      ZM: PropTypes.number,
      ZW: PropTypes.number
    })
  }).isRequired,
  onReady: PropTypes.func.isRequired
};

export default WorldMap;
